name: Lint

on:
  push:
    paths:
      - '*.py'
  workflow_dispatch:

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '>=3.11'
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Run mypy
        run: poetry run flake8 --max-line-length 88
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.11'
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Run mypy
        run: poetry run mypy .

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.11'
          architecture: x64
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry update
      - name: Run mypy
        run: poetry run black --line-length 88 --check .